development:
  adapter: postgresql
  database: charity_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: charity_test
  pool: 5
  timeout: 5000

production: 
  encoding: unicode
  adapter: postgresql
  username: username
  port: 5432
  host: hostname
  database: database
  password: password
